# Generated by Django 2.1.1 on 2018-12-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Playground', max_length=50, verbose_name='Name')),
                ('minX', models.IntegerField(verbose_name='Min X')),
                ('minY', models.IntegerField(verbose_name='Min Y')),
                ('maxX', models.IntegerField(verbose_name='Max X')),
                ('maxY', models.IntegerField(verbose_name='Max Y')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='X-Value')),
                ('y', models.IntegerField(verbose_name='Y-Value')),
                ('type', models.CharField(choices=[('corner', 'Playground Corner'), ('run_point', 'Point inside the Playground'), ('vector', 'Vector or Direction')], default=('corner', 'Playground Corner'), max_length=50, verbose_name='Point Type')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Playground', verbose_name='Playground')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Playground', max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='A',
            field=models.ForeignKey(limit_choices_to={'type': "('corner', 'Playground Corner')"}, on_delete=django.db.models.deletion.CASCADE, related_name='A', to='app.Point', verbose_name='Point A'),
        ),
        migrations.AddField(
            model_name='edge',
            name='B',
            field=models.ForeignKey(limit_choices_to={'type': ('corner', 'Playground Corner')}, on_delete=django.db.models.deletion.CASCADE, related_name='B', to='app.Point', verbose_name='Point B'),
        ),
        migrations.AddField(
            model_name='edge',
            name='Nr',
            field=models.ForeignKey(limit_choices_to={'type': ('vector', 'Vector or Direction')}, on_delete=django.db.models.deletion.CASCADE, related_name='Nr', to='app.Point', verbose_name='Normal Vector'),
        ),
        migrations.AddField(
            model_name='edge',
            name='Vr',
            field=models.ForeignKey(limit_choices_to={'type': ('vector', 'Vector or Direction')}, on_delete=django.db.models.deletion.CASCADE, related_name='Vr', to='app.Point', verbose_name='Direction Vector'),
        ),
        migrations.AddField(
            model_name='edge',
            name='playground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Playground', verbose_name='Playground'),
        ),
    ]
