# Generated by Django 2.1.4 on 2018-12-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minX', models.IntegerField(verbose_name='Min X')),
                ('minY', models.IntegerField(verbose_name='Min Y')),
                ('maxX', models.IntegerField(verbose_name='Max X')),
                ('maxY', models.IntegerField(verbose_name='Max Y')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='X-Value')),
                ('y', models.IntegerField(verbose_name='Y-Value')),
            ],
        ),
        migrations.AddField(
            model_name='playground',
            name='corners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corners', to='app.Point', verbose_name='Corners of Playground'),
        ),
        migrations.AddField(
            model_name='playground',
            name='edges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='app.Edge', verbose_name='Edges'),
        ),
        migrations.AddField(
            model_name='playground',
            name='run_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_points', to='app.Point', verbose_name='Running Points'),
        ),
        migrations.AddField(
            model_name='edge',
            name='A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A', to='app.Point', verbose_name='Point A'),
        ),
        migrations.AddField(
            model_name='edge',
            name='B',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B', to='app.Point', verbose_name='Point B'),
        ),
        migrations.AddField(
            model_name='edge',
            name='Nr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nr', to='app.Point', verbose_name='Normal Vector'),
        ),
        migrations.AddField(
            model_name='edge',
            name='Vr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vr', to='app.Point', verbose_name='Direction Vector'),
        ),
    ]
