# Generated by Django 2.1.4 on 2018-12-30 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('corner', 'Playground Corner'), ('run_point', 'Point inside the Playground'), ('vector', 'Vector or Direction')], default=('corner', 'Playground Corner'), max_length=50, verbose_name='Point Type'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='A',
            field=models.ForeignKey(limit_choices_to={'type': ('corner', 'Playground Corner')}, on_delete=django.db.models.deletion.CASCADE, related_name='A', to='app.Point', verbose_name='Point A'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='B',
            field=models.ForeignKey(limit_choices_to={'type': ('corner', 'Playground Corner')}, on_delete=django.db.models.deletion.CASCADE, related_name='B', to='app.Point', verbose_name='Point B'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='Nr',
            field=models.ForeignKey(limit_choices_to={'type': ('vector', 'Vector or Direction')}, on_delete=django.db.models.deletion.CASCADE, related_name='Nr', to='app.Point', verbose_name='Normal Vector'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='Vr',
            field=models.ForeignKey(limit_choices_to={'type': ('vector', 'Vector or Direction')}, on_delete=django.db.models.deletion.CASCADE, related_name='Vr', to='app.Point', verbose_name='Direction Vector'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='corners',
            field=models.ForeignKey(limit_choices_to={'type': ('corner', 'Playground Corner')}, on_delete=django.db.models.deletion.CASCADE, related_name='corners', to='app.Point', verbose_name='Corners of Playground'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='run_points',
            field=models.ForeignKey(limit_choices_to={'type': ('run_point', 'Point inside the Playground')}, on_delete=django.db.models.deletion.CASCADE, related_name='run_points', to='app.Point', verbose_name='Running Points'),
        ),
    ]
