# Generated by Django 2.1.4 on 2018-12-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='maxX',
            field=models.IntegerField(default=0, verbose_name='Max X'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='maxY',
            field=models.IntegerField(default=0, verbose_name='Max Y'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='minX',
            field=models.IntegerField(default=0, verbose_name='Min X'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='minY',
            field=models.IntegerField(default=0, verbose_name='Min Y'),
        ),
    ]
