# Generated by Django 2.1.4 on 2018-12-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181230_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='name',
            field=models.CharField(default='Playground', max_length=50, verbose_name='Playground Name'),
        ),
    ]
