# Generated by Django 2.1.4 on 2019-01-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190101_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='Nr',
            field=models.ForeignKey(limit_choices_to={'type': ('normal', 'Normal Vector')}, on_delete=django.db.models.deletion.CASCADE, related_name='Nr', to='app.Point', verbose_name='Normal Vector'),
        ),
    ]
