# Generated by Django 2.1.4 on 2018-12-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_playground_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='corners',
        ),
        migrations.RemoveField(
            model_name='playground',
            name='edges',
        ),
        migrations.RemoveField(
            model_name='playground',
            name='run_points',
        ),
        migrations.AddField(
            model_name='edge',
            name='playground',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Playground'),
        ),
        migrations.AddField(
            model_name='point',
            name='playground',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Playground'),
        ),
    ]
