# Generated by Django 2.1.4 on 2019-01-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190101_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[(1, 'Playground Corner'), (2, 'Point inside the Playground'), (3, 'Directional Vector'), (4, 'Normal Vector')], default=1, max_length=50, verbose_name='Point Type'),
        ),
    ]
