# Generated by Django 2.1.4 on 2019-01-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190101_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('corner', 'Playground Corner'), ('run_point', 'Point inside the Playground'), ('direction', 'Directional Vector'), ('normal', 'Normal Vector')], default='corner', max_length=50, verbose_name='Point Type'),
        ),
    ]
