# Generated by Django 2.1.4 on 2019-01-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190101_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='M',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='M', to='app.Point', verbose_name='Middle Point'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('corner', 'Playground Corner'), ('run_point', 'Point inside the Playground'), ('direction', 'Directional Vector'), ('normal', 'Normal Vector'), ('middle', 'Middle Point on Edge')], default='corner', max_length=50, verbose_name='Point Type'),
        ),
    ]
