# Generated by Django 2.1.4 on 2019-01-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190101_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='M',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M', to='app.Point', verbose_name='Middle Point'),
        ),
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.IntegerField(default=0, verbose_name='X-Value'),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Y-Value'),
        ),
    ]
