# Generated by Django 2.1.4 on 2019-01-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190101_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='maxX',
            field=models.FloatField(default=0.0, verbose_name='Max X'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='maxY',
            field=models.FloatField(default=0.0, verbose_name='Max Y'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='minX',
            field=models.FloatField(default=0.0, verbose_name='Min X'),
        ),
        migrations.AlterField(
            model_name='playground',
            name='minY',
            field=models.FloatField(default=0.0, verbose_name='Min Y'),
        ),
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.FloatField(verbose_name='X-Value'),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.FloatField(verbose_name='Y-Value'),
        ),
    ]
