# Generated by Django 2.1.4 on 2019-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190101_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
