# Generated by Django 2.1.4 on 2019-01-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_point3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point3d',
            name='playground',
        ),
        migrations.AddField(
            model_name='playground',
            name='laser',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='laserPos', to='app.Point3D', verbose_name='Laser Position'),
            preserve_default=False,
        ),
    ]
