# Generated by Django 2.1.4 on 2019-01-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190121_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='laser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laserPos', to='app.Point3D', verbose_name='Laser Position'),
        ),
    ]
