# Generated by Django 2.1.4 on 2019-01-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190121_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='laser',
        ),
        migrations.AddField(
            model_name='point3d',
            name='playground',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Playground', verbose_name='Playground'),
            preserve_default=False,
        ),
    ]
