# Generated by Django 2.1.4 on 2019-01-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190122_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point3d',
            name='playground',
        ),
        migrations.AddField(
            model_name='playground',
            name='laser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Point3D', verbose_name='Laserpointer'),
            preserve_default=False,
        ),
    ]
