# Generated by Django 2.1.4 on 2019-01-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190122_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playground',
            name='laser',
        ),
        migrations.AddField(
            model_name='point3d',
            name='playground',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Playground'),
            preserve_default=False,
        ),
    ]
